<a href="https://colab.research.google.com/github/MaulidyaAyu/DataMining/blob/main/DecisionTree-KelulusanMahasiswa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [77]:
#Import library numpy, pandas dan scikit-learn
import numpy as np
import pandas as pd
from sklearn import tree

In [78]:
#Membaca Dataset dari File ke Pandas dataFrame
irisDataset = pd.read_csv('kelulusanmhs.csv', delimiter=';', header=0)

In [79]:
irisDataset.head()

   ID  IPS 1  IPS 2  IPS 3  IPS 4  IPS 5  IPS 6  IPS 7  IPS 8  IPK   KELULUSAN
0   1   2.76   2.80   3.20   3.17   2.98   3.00   3.03    0.0  3.07  TERLAMBAT
1   2   3.00   3.30   3.14   3.14   2.84   3.13   3.25    0.0  3.17  TERLAMBAT
2   3   3.50   3.30   3.70   3.29   3.53   3.72   3.73    0.0  3.54  TERLAMBAT
3   4   3.17   3.41   3.61   3.36   3.48   3.63   3.46    0.0  3.41  TERLAMBAT
4   5   2.90   2.89   3.30   2.85   2.98   3.00   3.08    0.0  3.09  TERLAMBAT

In [80]:
#Mengubah kelas (kolom "Species") dari String ke Unique-Integer
irisDataset["KELULUSAN"] = pd.factorize(irisDataset.KELULUSAN)[0]

In [81]:
irisDataset.head()

   ID  IPS 1  IPS 2  IPS 3  IPS 4  IPS 5  IPS 6  IPS 7  IPS 8  IPK   KELULUSAN
0   1   2.76   2.80   3.20   3.17   2.98   3.00   3.03    0.0  3.07          0
1   2   3.00   3.30   3.14   3.14   2.84   3.13   3.25    0.0  3.17          0
2   3   3.50   3.30   3.70   3.29   3.53   3.72   3.73    0.0  3.54          0
3   4   3.17   3.41   3.61   3.36   3.48   3.63   3.46    0.0  3.41          0
4   5   2.90   2.89   3.30   2.85   2.98   3.00   3.08    0.0  3.09          0

In [82]:
print(irisDataset)

      ID  IPS 1  IPS 2  IPS 3  IPS 4  IPS 5  IPS 6  IPS 7  IPS 8  IPK   \
0      1   2.76   2.80   3.20   3.17   2.98   3.00   3.03    0.0  3.07
1      2   3.00   3.30   3.14   3.14   2.84   3.13   3.25    0.0  3.17
2      3   3.50   3.30   3.70   3.29   3.53   3.72   3.73    0.0  3.54
3      4   3.17   3.41   3.61   3.36   3.48   3.63   3.46    0.0  3.41
4      5   2.90   2.89   3.30   2.85   2.98   3.00   3.08    0.0  3.09
..   ...    ...    ...    ...    ...    ...    ...    ...    ...   ...
374  375   1.98   2.50   2.14   2.77   2.61   2.93   2.82    2.5  0.99
375  376   2.74   2.75   2.55   3.00   2.98   2.80   3.14    3.0  2.97
376  377   2.74   2.75   2.55   3.00   2.98   2.80   3.14    3.0  3.03
377  378   3.02   2.94   3.25   2.87   3.00   2.94   3.09    3.0  3.16
378  379   3.10   3.06   3.00   3.23   2.79   3.00   2.41    3.0  2.16

     KELULUSAN
0            0
1            0
2            0
3            0
4            0
..         ...
374          1
375          1
376          1
377          1
378          1

[379 rows x 11 columns]

In [83]:
#Menghapus kolom "Id"
irisDataset = irisDataset.drop(labels="ID", axis=1)

In [84]:
print(irisDataset)

     IPS 1  IPS 2  IPS 3  IPS 4  IPS 5  IPS 6  IPS 7  IPS 8  IPK   KELULUSAN
0     2.76   2.80   3.20   3.17   2.98   3.00   3.03    0.0  3.07          0
1     3.00   3.30   3.14   3.14   2.84   3.13   3.25    0.0  3.17          0
2     3.50   3.30   3.70   3.29   3.53   3.72   3.73    0.0  3.54          0
3     3.17   3.41   3.61   3.36   3.48   3.63   3.46    0.0  3.41          0
4     2.90   2.89   3.30   2.85   2.98   3.00   3.08    0.0  3.09          0
..     ...    ...    ...    ...    ...    ...    ...    ...   ...        ...
374   1.98   2.50   2.14   2.77   2.61   2.93   2.82    2.5  0.99          1
375   2.74   2.75   2.55   3.00   2.98   2.80   3.14    3.0  2.97          1
376   2.74   2.75   2.55   3.00   2.98   2.80   3.14    3.0  3.03          1
377   3.02   2.94   3.25   2.87   3.00   2.94   3.09    3.0  3.16          1
378   3.10   3.06   3.00   3.23   2.79   3.00   2.41    3.0  2.16          1

[379 rows x 10 columns]

In [85]:
#Mengubah dataFrame ke array Numpy
irisDataset = irisDataset.to_numpy()

In [86]:
print(irisDataset)

[[2.76 2.8  3.2  ... 0.   3.07 0.  ]
 [3.   3.3  3.14 ... 0.   3.17 0.  ]
 [3.5  3.3  3.7  ... 0.   3.54 0.  ]
 ...
 [2.74 2.75 2.55 ... 3.   3.03 1.  ]
 [3.02 2.94 3.25 ... 3.   3.16 1.  ]
 [3.1  3.06 3.   ... 3.   2.16 1.  ]]

In [87]:
#Membagi Dataset => 80 baris data untuk training dan 20 baris data untuk testing
dataTraining = np.concatenate((irisDataset[0:40, :], irisDataset[50:90, :]),
                              axis=0)
dataTesting = np.concatenate((irisDataset[40:50, :], irisDataset[90:100, :]),
                             axis=0)

In [88]:
print(dataTesting)
len(dataTesting)

[[2.29 3.09 3.2  2.74 2.65 2.37 2.83 3.   2.96 0.  ]
 [2.71 2.59 3.09 1.76 3.06 2.77 3.66 3.22 3.09 0.  ]
 [2.43 3.02 3.   2.79 2.75 2.59 3.08 2.63 2.9  0.  ]
 [2.88 2.59 2.82 3.05 2.65 3.03 3.3  2.   3.03 0.  ]
 [2.07 2.59 2.59 2.48 2.52 2.89 3.04 3.   2.77 0.  ]
 [3.1  3.   2.98 3.1  3.25 3.26 3.46 0.   3.17 0.  ]
 [2.57 2.55 2.57 1.91 2.33 2.45 2.19 2.55 2.94 0.  ]
 [3.26 3.73 3.02 3.5  2.69 3.33 3.09 3.5  3.24 1.  ]
 [2.71 2.89 2.75 3.18 3.19 3.22 3.73 0.   3.2  1.  ]
 [1.9  1.91 1.59 1.28 1.37 2.83 2.2  2.7  2.66 0.  ]
 [2.86 2.7  2.89 2.73 2.41 3.19 2.07 1.21 2.92 0.  ]
 [2.33 2.75 2.36 2.18 1.73 2.64 2.25 2.28 2.49 0.  ]
 [2.45 1.43 2.16 0.27 0.44 1.28 0.66 0.29 1.82 0.  ]
 [3.24 3.83 3.65 3.61 3.69 3.73 3.7  0.   3.63 1.  ]
 [2.24 3.14 1.9  1.89 1.63 2.39 1.75 1.45 2.18 0.  ]
 [2.74 2.41 2.75 2.86 1.68 3.13 2.52 0.88 2.81 0.  ]
 [2.31 2.77 2.64 2.82 2.75 3.06 2.97 3.5  2.71 0.  ]
 [2.62 3.02 2.52 2.91 2.55 2.81 2.36 0.   2.83 0.  ]
 [2.67 2.89 2.66 2.45 2.05 2.66 1.67 1.2  2.53 0.  ]
 [2.74 3.   2.98 2.86 2.61 2.43 2.48 0.93 2.74 0.  ]]

20

In [89]:
#Memecah Dataset ke Input dan Label
inputTraining = dataTraining[:, 0:9]
inputTesting = dataTesting[:, 0:9]
labelTraining = dataTraining[:, 9]
labelTesting = dataTesting[:, 9]

In [90]:
#Mendefinisikan Decision Tree Classifier
model = tree.DecisionTreeClassifier()

In [92]:
#Mentraining Model
from sklearn.impute import SimpleImputer

# Membuat objek SimpleImputer dengan strategi pengisian 'mean'
imputer = SimpleImputer(strategy='mean')

# Menggunakan SimpleImputer untuk mengisi nilai-nilai yang hilang dalam data
inputTraining = imputer.fit_transform(inputTraining)
model = model.fit(inputTraining, labelTraining)

In [94]:
#Memprediksi Input Data Testing
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [0. 0. 0. 0. 0. 0. 0. 1. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0.]
Hasil Prediksi :  [1. 0. 1. 0. 1. 0. 1. 1. 0. 0. 0. 0. 1. 1. 0. 0. 1. 0. 0. 0.]

In [95]:
#Menghitung Akurasi
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar :", prediksiBenar, "data")
print("Prediksi Salah :", prediksiSalah, "data")
print("Akurasi :", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar : 13 data
Prediksi Salah : 7 data
Akurasi : 65.0 %